---
# Default variables for kubernetes role

# kubectl major version (used for apt repository)
k8s_kubectl_major_version: "1.29"

# k9s version
k8s_k9s_version: "0.31.9"

# kubectx/kubens version
k8s_kubectx_version: "0.9.5"
